remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Validation Rules Documentation]
description: [Welcome to the Validation Rules Documentation! This guide provides detailed information on various validation rules, including their titles, descriptions, and examples of how to use them in your schema.]
